// Code generated by protoc-gen-go. DO NOT EDIT.
// source: depart.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	depart.proto

It has these top-level messages:
	User
	ChildDepart
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId int32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	WithMe bool  `protobuf:"varint,2,opt,name=withMe" json:"withMe,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetWithMe() bool {
	if m != nil {
		return m.WithMe
	}
	return false
}

type ChildDepart struct {
	Depart []int32 `protobuf:"varint,1,rep,packed,name=depart" json:"depart,omitempty"`
}

func (m *ChildDepart) Reset()                    { *m = ChildDepart{} }
func (m *ChildDepart) String() string            { return proto1.CompactTextString(m) }
func (*ChildDepart) ProtoMessage()               {}
func (*ChildDepart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChildDepart) GetDepart() []int32 {
	if m != nil {
		return m.Depart
	}
	return nil
}

func init() {
	proto1.RegisterType((*User)(nil), "proto.User")
	proto1.RegisterType((*ChildDepart)(nil), "proto.ChildDepart")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Depart service

type DepartClient interface {
	GetAllChildDepartByUserId(ctx context.Context, in *User, opts ...grpc.CallOption) (*ChildDepart, error)
}

type departClient struct {
	cc *grpc.ClientConn
}

func NewDepartClient(cc *grpc.ClientConn) DepartClient {
	return &departClient{cc}
}

func (c *departClient) GetAllChildDepartByUserId(ctx context.Context, in *User, opts ...grpc.CallOption) (*ChildDepart, error) {
	out := new(ChildDepart)
	err := grpc.Invoke(ctx, "/proto.Depart/GetAllChildDepartByUserId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Depart service

type DepartServer interface {
	GetAllChildDepartByUserId(context.Context, *User) (*ChildDepart, error)
}

func RegisterDepartServer(s *grpc.Server, srv DepartServer) {
	s.RegisterService(&_Depart_serviceDesc, srv)
}

func _Depart_GetAllChildDepartByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartServer).GetAllChildDepartByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Depart/GetAllChildDepartByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartServer).GetAllChildDepartByUserId(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Depart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Depart",
	HandlerType: (*DepartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllChildDepartByUserId",
			Handler:    _Depart_GetAllChildDepartByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depart.proto",
}

func init() { proto1.RegisterFile("depart.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0x48,
	0x2c, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x66, 0x5c, 0x2c,
	0xa1, 0xc5, 0xa9, 0x45, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x1e, 0x48, 0xbc, 0x3c, 0xb3, 0x24, 0xc3, 0x37, 0x55, 0x82,
	0x49, 0x81, 0x51, 0x83, 0x23, 0x08, 0xca, 0x53, 0x52, 0xe5, 0xe2, 0x76, 0xce, 0xc8, 0xcc, 0x49,
	0x71, 0x01, 0x9b, 0x09, 0x52, 0x06, 0x31, 0x5d, 0x82, 0x51, 0x81, 0x19, 0xa4, 0x1d, 0xc2, 0x33,
	0xf2, 0xe0, 0x62, 0x83, 0xaa, 0xb0, 0xe3, 0x92, 0x74, 0x4f, 0x2d, 0x71, 0xcc, 0xc9, 0x41, 0xd2,
	0xe6, 0x54, 0x19, 0x0a, 0xb1, 0x85, 0x1b, 0xe2, 0x28, 0x3d, 0x10, 0x57, 0x4a, 0x08, 0xca, 0x41,
	0x52, 0xa8, 0xc4, 0xe0, 0xa4, 0xc2, 0x25, 0x9c, 0x99, 0xaf, 0x97, 0x5e, 0x54, 0x90, 0xac, 0x57,
	0x94, 0x94, 0x98, 0xac, 0x07, 0xb1, 0xc0, 0x89, 0x1b, 0xa2, 0x20, 0x00, 0xa4, 0x23, 0x80, 0x31,
	0x89, 0x0d, 0xac, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x87, 0xd9, 0x73, 0xa8, 0xec, 0x00,
	0x00, 0x00,
}
